brew "awscli"
brew "bat" # better cat
brew "brew-gem"
brew "btop" # better htop
# brew "cmake"
brew "direnv" # directory specific environment variables
brew "docker-compose"
# brew "docker-credential-helper"
brew "dvc" # data version control
brew "eza" # ls replacement
brew "fd" # find replacement
brew "fribidi" # required for textshaping (R package)
brew "fzf"
brew "gcc"
# brew "gdal" # geospatial data
brew "gh"
brew "harfbuzz" # required for textshaping (R package)
brew "htop"
brew "jq"
brew "lazygit"
brew "libpng"
brew "luarocks"
brew "mono"
brew "node"
brew "nvim"
brew "openapi-generator"
brew "opencode"
brew "openssl"
brew "pandoc"
brew "podman" # containers 
brew "podman-compose"
brew "pulumi" # infrastructure as code
# brew "python@3.9"
# brew "python@3.10"
# brew "python@3.11"
brew "python@3.12"
# brew "python@3.13"
# brew "python@3"
# brew "r"
brew "r-rig"
brew "ripgrep"
brew "ruby"
# brew "speedtest-cli"
brew "sqlite"
brew "starship"
brew "tealdeer" # man / tldr
tap "hashicorp/tap"
brew "hashicorp/tap/terraform"
# brew "thefuck" # correct cli typos
# brew "tippecanoe" # vector tiles from geojson
# brew "tldr" # better man pages
# brew "tmux"
# brew "tree" # recursive ls 
# brew "udunits"
brew "ugrep" # replacement for grep
brew "uv" # python dependency management in Rust
brew "uvicorn" # a webserver
# brew "vim" # text editing
brew "vite" 
brew "zoxide"

cask "font-meslo-lg-nerd-font"
